### ISSUE TITLE
how to get the uploaded file name yet?

### ISSUE THREAD

**Issue by janily** [weixiyen/jquery-filedrop#135]
i want to get the file name.
i use the "file.name" is not work,so in filedrop how to get the uploaded file name yet?
thanks~~~!

**Comment by boughtonp** [comment]
Change this line:

	xhr.open(opts.requestType, opts.url(), true);

To this:

	xhr.open(opts.requestType, opts.url(upload), true);


Then you can do...

	FiledropContainer.filedrop({
		...
		url: function(upload)
			{
				// ...
				if ( FileList.indexOf(upload.file.name) > -1 )
				{
					if ( confirm("The File "+upload.file.name+" exists, overwrite the file?") )
						{
						// ...
						}
				}
				// ...
			}
		...
